version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql:
  frontend:
    image: node:alpine
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=metro-ag"
      - "MYSQL_DATABASE=metro-ag"
      - "MYSQL_USER=metro-ag"
      - "MYSQL_PASSWORD=metro-ag"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10